DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS student;
CREATE TABLE student (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER UNIQUE NOT NULL,
    has_disability INTEGER NOT NULL
);

DROP TABLE IF EXISTS staff;
CREATE TABLE staff (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

DROP TABLE IF EXISTS driver;
CREATE TABLE driver (
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

DROP TABLE IF EXISTS rides;
CREATE TABLE rides (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    start_address TEXT NOT NULL,
    end_address TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time TIMESTAMP NOT NULL,
    -- date TEXT NOT NULL,
    -- time TEXT NOT NULL,
    driver TEXT,
    FOREIGN KEY (author_id) REFERENCES accounts (id)
);
